apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql-deploy
  name: mysql-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-deploy
  template:
    metadata:
      labels:
        app: mysql-deploy
    spec:
      containers:
      - image: mysql:5.7
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: J12345j
          # valueFrom:
          #   secretKeyRef:
          #     key: mysql_root_password
          #     name: mysql-secret
        - name: MYSQL_PASSWORD
          value: Clarusway_1
          # valueFrom:
          #   secretKeyRef:
          #     key: mysql_admin_password
          #     name: Q2xhcnVzd2F5XzE=
        - name: MYSQL_USER
          value: clarus
          # valueFrom:
          #   configMapKeyRef:
          #     key: MYSQL_USER
          #     name: mysql-config
        - name: MYSQL_DATABASE
          value: phonebook
          # valueFrom:
          #   configMapKeyRef:
          #     key: MYSQL_DATABASE
          #     name: mysql-config
        resources: {}
        volumeMounts:
          - name: mysql-persistent-volume
            mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-volume
          persistentVolumeClaim:
            claimName: mysql-pv-claim