apiVersion: v1
kind: Service
metadata:
  name: resultserver-svc
  labels:
    app: resultserver-deploy
spec:
  #type: LoadBalancer # --> not working for now...
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30002
      protocol: TCP
  selector:
    app: resultserver-deploy